"""Update patient field name

Revision ID: b2fb50152f41
Revises: d82b7571cd19
Create Date: 2019-01-17 13:38:43.700851

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b2fb50152f41'
down_revision = 'd82b7571cd19'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('appointments', sa.Column('patient_id', sa.Integer(), nullable=True))
    op.drop_constraint('appointments_patient_fkey', 'appointments', type_='foreignkey')
    op.create_foreign_key(None, 'appointments', 'patients', ['patient_id'], ['id'])
    op.drop_column('appointments', 'patient')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('appointments', sa.Column('patient', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'appointments', type_='foreignkey')
    op.create_foreign_key('appointments_patient_fkey', 'appointments', 'patients', ['patient'], ['id'])
    op.drop_column('appointments', 'patient_id')
    # ### end Alembic commands ###
