"""Update patient field name

Revision ID: bd3b4291065e
Revises: b2fb50152f41
Create Date: 2019-01-17 13:57:43.618288

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bd3b4291065e'
down_revision = 'b2fb50152f41'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('patients', 'gender')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('patients', sa.Column('gender', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
