"""Add appointments app

Revision ID: d82b7571cd19
Revises: 921f6f3890fd
Create Date: 2019-01-17 13:32:05.609740

"""
import sqlalchemy_utils
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'd82b7571cd19'
down_revision = '921f6f3890fd'
branch_labels = None
depends_on = None

GENDER = [
    (1, 'M'),
    (2, 'F'),
    (3, '')
]


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('appointments',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('patient', sa.Integer(), nullable=True),
                    sa.Column('date', sa.Date(), nullable=False),
                    sa.ForeignKeyConstraint(['patient'], ['patients.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.add_column('patients', sa.Column('birth_date', sa.Date(), nullable=False))
    op.add_column('patients', sa.Column('first_name', sa.String(), nullable=False))
    op.add_column('patients',
                  sa.Column('gender', sqlalchemy_utils.types.choice.ChoiceType(choices=GENDER), nullable=True))
    op.add_column('patients', sa.Column('last_name', sa.String(), nullable=True))
    op.drop_column('patients', 'fullname')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('patients', sa.Column('fullname', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('patients', 'last_name')
    op.drop_column('patients', 'gender')
    op.drop_column('patients', 'first_name')
    op.drop_column('patients', 'birth_date')
    op.drop_table('appointments')
    # ### end Alembic commands ###
