version: '3.3'
services:
   ccm:
     build:
      context: .
      dockerfile: Dockerfile-dev
     image: api:dev
     volumes:
       - .:/usr/src/
     env_file:
      - dev.env
     ports:
       - "8000:8000"
     restart: unless-stopped
     deploy:
      placement:
        constraints:
          - node.labels.type==code
      replicas: 1
      update_config:
        parallelism: 1
        delay: 10s
   db:
     image: postgres:11.1
     volumes:
       - db:/var/lib/postgresql/data
     environment:
       - POSTGRES_DB=ccm_db
       - POSTGRES_USER=ccm_user
       - POSTGRES_PASSWORD=ccm_pwd
     deploy:
       placement:
         constraints:
           - node.labels.type==database
       replicas: 1
       update_config:
         parallelism: 1
         delay: 10s

volumes:
  db: